title: AP 210
description: AP 210, the product model exchange standard
# The above two are used by jekyll-seo-tag for things such as
# `<title>` and `<meta>` tags, as well as elsewhere by the theme.

permalink: /blog/:year-:month-:day-:title/

# url: http://localhost:8080
# No trailing slash.

github_repo_url: https://github.com/expresslang/ap210.org
github_repo_branch: main

algolia_search:
  api_key: 'test'
  index_name: 'ap210'

tagline: >-
  Welcome to AP 210!

landing_priority: [custom_intro, blog, specs, software]

theme: jekyll-theme-open-project

author:
  name: EXPRESS Language Foundation
  url: https://www.expresslang.org

authors:
  - name: EXPRESS Language Foundation
    email: contact@expresslang.org

contact_email: contact@expresslang.org

theme: jekyll-theme-open-project

# TODO: Replace by EXPRESS Language Foundation own site setup
# and remove the `/parent-hub` directory after that.
# parent_hub:
#   git_repo_url: https://github.com/expresslang/ap210.org
#   git_repo_branch: main
#   home_url: https://www.ap210.org/

includes_dir: '.'

social:
  links:
    - https://github.com/expresslang

legal:
  name: EXPRESS Language Foundation
  tos_link: /tos
  privacy_policy_link: /privacy

home_calls_to_action:
  - { url: "/docs/test-section/", title: "View documentation" }

collections:
  projects:
    output: false
  software:
    output: true
    permalink: /software/:path/
  specs:
    output: true
    permalink: /specs/:path/
  posts:
    output: true
    permalink: /blog/:year-:month-:day-:title/
  pages:
    output: true
    permalink: /:name/


defaults:
  # Theme defaults.
  # MUST be duplicated from theme’s _config.yml
  # (does not get inherited, unlike the collections hash)
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
  - scope:
      path: _software
      type: software
    values:
      layout: product
  - scope:
      path: _specs
      type: specs
    values:
      layout: spec

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

tag_namespaces:
  software:
    writtenin: "Written in"
    bindingsfor: "Bindings for"
    user: "Target user"
    interface: "Interface"
  specs:
    audience: "Audience"
    completion_status: "Status"

exclude:
  - .git
  - .lycheeignore
  - "*/.git"
  - Gemfile*
  - Makefile
  - Rakefile
  - README.adoc
  - vendor # for deployment

collections:
  research:
    output: true
    permalink: /application/research/:name/
