= AP210.org open project Site

== Introduction

This is the site for AP210, part of EXPRESS Language Foundation projects, located
at https://www.ap210.org.

It is a https://jekyllrb.com[Jekyll]-based site created with the Open Project
Jekyll theme.

Refer to their respective docs for details.

== Content management

Unlike other sections, this section targets site author
who does not necessarily have a software engineering background.

NOTE: This documentation covers macOS or Ubuntu Linux.

=== Overview

Content management workflow involves the following phases:

. Authoring: changing the contents of the repository.
  You’ll manipulate AsciiDoc files (`.adoc` file extension)
  and related files such as illustrations.

. Previewing your changes (optional):
  building and previewing the new version of the site locally without publishing.
  (This is not a strict requirement at early stages,
  you can skip straight to the next step and see your changes live.
  However, setting up for this step is beneficial since it allows you
  to preview your changes quicker.)

. Version management: relaying your changes to upstream repository.
  This means others will see your changes.
  This also will cause the new version of the site to be published.
  (Publishing the new version may take a few minutes.)

=== Setup

==== Pre-requisites

Make sure you have the installed:

- A text editor
  (you can use a simple editor like CotEditor on macOS or Notepad+ on Windows,
  or something more complex like VS Code with support for AsciiDoc preview)
- Git CLI

=== Authoring

Key sections are documentation pages (the largest) and news/blog posts.
Apart from that there can be other standalone pages.

==== Documentation

Documentation lives under the /docs/ directory.

The structure of the directory is reflected in the structure of URLs.
For example, file /docs/section-1/test-page.adoc will be available under ap210.org/docs/section-1/test-page/.

===== Navigation sidebar

Documentation requires manual update when you add pages, retitle them
or move them around.

Navigation across the docs lives _separately from documentation files_:
you can find it under /_layouts/docs.html.

The YAML frontmatter of the file (between `---` delimiters`) contains
`navigation` key, under which documentation structure is described.
The sidebar is generated from this structure.

===== The Deliverables page

==== Posts

==== Other pages

== Previewing site locally

=== Getting started

. Ensure you have reasonable Ruby version (2.7.5 is recommended).
  Use rbenv to manage Ruby versions.

. Run `bundle` from within site directory to install Ruby dependencies.

=== Building & serving

Run `jekyll serve` from within site directory.

Alternatively, build to HTML and serve separately
with `jekyll build && cd _site && python3 -m http.server`.

To troubleshoot errors, append ` --trace` to build or serve command.

== Development workflow

. Ensure site builds and works normally, tests pass
. Create your feature branch (`git checkout -b my-new-feature`)
. Commit your changes (`git commit -am 'Add some feature'`)
. Push to the branch (`git push origin my-new-feature`)
. Make a pull request
