---
title: Testcase template
layout: docs
permalink: /application/test-cases/template/
---

== Template

Filename::
`FILENAME.stp`

Author::
AUTHOR

Title::
A SINGLE LINE TITLE

Primary test case scope::
Scope

Description::
TEXTUAL DESCRIPTION

Supporting Graphic(s)::

Figure 1: Primary Surface View

Design Source::
DESIGN SOURCE

Source Schema name::
SOURCE SCHEMA

Source Schema Date::
Mon Sep  4 18:51:43 EDT 2017

Validation Schema Date::
Mon Sep  4 18:51:43 EDT 2017

Validation Schema version::
Mon Sep  4 18:51:43 EDT 2017

Recommended Practice Reference::
RECPRAC REFERENCE

Translator::
SOURCE TRANSLATOR

PostProcessing::
POST PROCESSING DESCRIPTION

Test Purpose::
TEST PURPOSE DESCRIPTION

Applicable Rules Clauses::
RULE LIST

Issues::
N/A

Validation properties::
link to validation properties data set

Testing History::
TEST HISTORY


== Acknowledgement

This test case structure is derived from the PDES Inc., electrical project test
case template.

== Sample test case

link:../design0_fmt.stp[`design0_fmt.stp`]
