#ifndef LOCATING_OR_REFINEMENT_SURFACE_PROFILE_TOLERANCE_H
#define LOCATING_OR_REFINEMENT_SURFACE_PROFILE_TOLERANCE_H

// Enumerations
union locating_or_refinement_surface_profile_tolerance {
   class composite_surface_profile_locating_tolerance *ST_composite_surface_profile_locating_tolerance;
   class composite_surface_profile_refinement_tolerance *ST_composite_surface_profile_refinement_tolerance;
   };

#endif
