#ifndef CONSTRAINING_ELEMENT_DEFINITIONS_H
#define CONSTRAINING_ELEMENT_DEFINITIONS_H

// Enumerations
union constraining_element_definitions {
   class tolerance_zone_definition *ST_tolerance_zone_definition;
   class profile_related_positional_boundary_definition *ST_profile_related_positional_boundary_definition;
   class positional_boundary_member_definition *ST_positional_boundary_member_definition;
   class conical_tolerance_zone_boundary_diametrical_size_characteristic *ST_conical_tolerance_zone_boundary_diametrical_size_characteristic;
   };

#endif
