#ifndef DESIGN_INTENT_MODIFICATION_PLANAR_SHAPE_SELECT_H
#define DESIGN_INTENT_MODIFICATION_PLANAR_SHAPE_SELECT_H

// Enumerations
union design_intent_modification_planar_shape_select {
   class design_intent_modification_styled_area_representation *ST_design_intent_modification_styled_area_representation;
   class design_intent_modification_planar_shape *ST_design_intent_modification_planar_shape;
   };

#endif
