#ifndef LOCATING_OR_REFINEMENT_LINEAR_PROFILE_TOLERANCE_H
#define LOCATING_OR_REFINEMENT_LINEAR_PROFILE_TOLERANCE_H

// Enumerations
union locating_or_refinement_linear_profile_tolerance {
   class composite_linear_profile_locating_tolerance *ST_composite_linear_profile_locating_tolerance;
   class composite_linear_profile_refinement_tolerance *ST_composite_linear_profile_refinement_tolerance;
   };

#endif
