// GENERATED BY ECCO V3.1.2
// - debug
#ifndef _EX_INIT_H
#define _EX_INIT_H
extern "C" int schema_begin();
extern "C" int schema_init();
extern "C" void schema_end();
void runtime_system_initialize(unsigned, unsigned, ...);
void runtime_system_end();
int interpreter_start_impl(int argc,char** argv, int mode);
int interpreter_assign_adr_impl(void (**sym)());
void set_address_resolver_impl(void* (*res)(void*, const char*), void* h);
extern signed char _tmp[];
void begin_Ap210_armS18();
void init_Ap210_armS18();
void end_Ap210_armS18();
void close_Ap210_armS18();
#endif //!_EX_INIT_H
